version: "3.7"
services:
  mongodb_container:
    container_name: consumer-database-service
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - consumer-database-service

volumes:
  mongodb_data_container:

networks:
  consumer-database-service:
    name: learnlogy-network
