version: "3"
services:
  proxy-service:
    container_name: proxy-service
    restart: always
    build: ./proxy-service
    ports:
      - "3000:3000"
    links:
      - consumer-database-service
      - cache-memory-service
  consumer-database-service:
    restart: always
    container_name: consumer-database-service
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    volumes:
      - ./volumes/consumer-database-service:/data/db
  cache-memory-service:
    restart: always
    container_name: cache-memory-service
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./volumes/cache-memory-service:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=cache-memory-service
    ports:
      - "8081:8081"
    links:
      - cache-memory-service
volumes:
  cache-memory-service-volume:
  consumer-database-service-volume:
