version: '3'
services:
  proxy-service:
    container_name: proxy-service
    restart: always
    build: ./proxy-service
    ports:
      - '3000:3000' 
    links: 
      - consumer-database-service
      - cache-memory-service
  consumer-database-service:
    restart: always
    container_name: consumer-database-service
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
  cache-memory-service:
    restart: always
    container_name: cache-memory-service
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  redis-commander-cache-memory-service:
    restart: always
    container_name: redis-commander-cache-memory-service
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - cache-memory-service

volumes:
  redis-data: