### login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123"
}

### logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "admin@email.co.th",
    "username" : "admin",
    "password" : "123"
}

### refresh-token
POST http://localhost:3000/auth/refresh-token

### get all role
GET http://localhost:3000/role/

### add role
POST http://localhost:3000/role/
Content-Type: application/json

{
    "name" : "admin",
    "discription" : "role for management all resource (Biggest role)"
}