version: "3.7"

services:
  redis:
    container_name: cache-memory-service
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - cache-memory-service

  redis-commander:
    container_name: redis-commander-cache-memory-service
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - redis-commander-cache-memory-service

volumes:
  redis-data:

networks:
  cache-memory-service:
    name: learnlogy-network
  redis-commander-cache-memory-service:
    name: learnlogy-network